services:
  - type: web
    name: air-afrique-observatoire
    runtime: node
    plan: free
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: ADMIN_TOKEN
        generateValue: true
